Testing branch ( Setup mobile version skeleton )
ABDULALI3468/MY_PORTFOLIO pull request #1
Opened 2022-03-17 10:23 UTC by ABDULALI3468

In this, I have created the first page of my portfolio website.

2022-03-17 11:44 UTC, sja-thedude reviewed
Hi @ABDULALI3468, This is @sja-thedude your code reviewer.

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have a professional readme. Kindly add the readme from [here](https://github.com/microverseinc/readme-template) and make changes accordingly.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-03-17 16:25 UTC, BenMukebo requested changes
## Hi *** @ABDULALI3468, *** 🤝 

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!

### To highlight 💪🏻

- No linter errors. ✔️ 
- Github flow was correctly used.  ✔️   
- Good commit messages ✔️ 
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_

- [ ] Please, Write a meaningful title for your pull request and always add a short summary of changes introduced in the pull request. you can check the  [Professional repo - basic rules](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md)

- [ ] Your pull request has conflict with the base branch, please resolve them for the second submission

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏 💻  

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @BenMukebo ) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-19 23:26 UTC, Hamzaoutdoors requested changes
Hey @ABDULALI3468, I am **Hamza** your reviewer for this PR 😸 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![image](https://media.giphy.com/media/42AFvimyQTNQW44PNG/giphy.gif)

## To Highlight
✔️ The repo looks professional
✔️ Git/GitHub flow best practices have been followed
✔️ There are no linter errors
✔️ You have a descriptive README

## Required Changes ♻️

_See the inline comments below for more required changes 😃_  

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
**N.A**

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @hamzaoutdoors in your question so I can receive the notification ^_^

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-19 23:26 UTC, Hamzaoutdoors commented on index.html
> +            <h2>Welcome</h2>
- [ ] As mentioned by the previous reviewer the logo should be in an anchor tag `<a>` so when a user click on it, he can return to the main section, kindly try to refactor this line to be something like that :

`<a class="logo" href="#">Abdulali</a>`

2022-03-19 23:48 UTC, ABDULALI3468 commented
I have made the changes please approve it.

On Sun, Mar 20, 2022, 4:27 AM Hamza Ellaouzi ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hey @ABDULALI3468 <https://github.com/ABDULALI3468>, I am *Hamza* your
> reviewer for this PR 😸
>
> Good job so far!
> There are some issues that you still need to work on to go to the next
> project but you are almost there!
>
> [image: image]
> <https://camo.githubusercontent.com/8dd93996746e7aee71ac4dbe5acb5a8f7e081f8f2cbe18d48a489837cf5cf5aa/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f3432414676696d7951544e51573434504e472f67697068792e676966>
> To Highlight
>
> ✔️ The repo looks professional
> ✔️ Git/GitHub flow best practices have been followed
> ✔️ There are no linter errors
> ✔️ You have a descriptive README
> Required Changes ♻️
>
> *See the inline comments below for more required changes 😃*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> You can also consider:
> *N.A*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag @Hamzaoutdoors <https://github.com/Hamzaoutdoors>
> in your question so I can receive the notification ^_^
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In index.html
> <https://github.com/ABDULALI3468/MY_PORTFOLIO/pull/1#discussion_r830538029>
> :
>
> > +<!DOCTYPE html>
>
> +<html lang="en">
>
> +<head>
>
> +    <meta charset="UTF-8">
>
> +    <link rel="stylesheet" href="MYSTYLES.css">
>
> +    <meta http-equiv="X-UA-Compatible" content="IE=edge">
>
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0">
>
> +    <title>My mobile portfolio</title>
>
> +    <link rel="preconnect" href="https://fonts.googleapis.com">
>
> +    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
>
> +    <link ***@***.***;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
>
> +</head>
>
> +<body>
>
> +    <section class="firstpage">
>
> +        <nav class="header">
>
> +            <h2>Welcome</h2>
>
>
>
>    - As mentioned by the previous reviewer the logo should be in an
>    anchor tag <a> so when a user click on it, he can return to the main
>    section, kindly try to refactor this line to be something like that :
>
> <a class="logo" href="#">Abdulali</a>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ABDULALI3468/MY_PORTFOLIO/pull/1#pullrequestreview-915042427>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWO3YB4FMQYBC43MJ2WZ7VTVAZPENANCNFSM5Q6QFTQQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-03-20 00:10 UTC, Omar-Muhamad reviewed
Hi @ABDULALI3468 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] You have submitted a project, that linters checks not working at all please fix that and make sure that all linters checks are ok and green.

- [ ] Please fix the Pull Request conflict issue to be able to merge it.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

2022-03-20 01:55 UTC, Gambit142 approved these changes
Hi @ABDULALI3468 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-20 01:55 UTC, Gambit142 commented on index.html
> +            </h1>
- [ ] (Optional) Nice attempt trying to implement the changes suggested by a previous reviewer. I think it would be nice to wrap the text _**I'm a software developer**_ in a `<p>` tag instead of a `span` tag. `<span>` tags are not block-level elements, so whenever they are used, they appear inline of their parent element on a web page. Try to make your design identical to the Figma template you chose.

### Your Design

![image](https://user-images.githubusercontent.com/77106962/159144613-4b8f4d3d-e1cf-4675-a965-43068fb3e45b.png)

### Figma Design

![image](https://user-images.githubusercontent.com/77106962/159144625-bc4b3723-1404-4490-8826-a83c5c5d369b.png)

2022-03-20 01:56 UTC, ABDULALI3468 commented
Thanks alot. Now I will definitely make this promise true.

On Sun, Mar 20, 2022, 6:55 AM Francis Ugorji ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> Hi @ABDULALI3468 <https://github.com/ABDULALI3468> 👋,
>
> Your project is complete! There is nothing else to say other than... it's
> time to merge it [image: :shipit:]
> Congratulations! 🎉
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In index.html
> <https://github.com/ABDULALI3468/MY_PORTFOLIO/pull/1#discussion_r830547380>
> :
>
> > +            <h1 class="intro">
>
> +                Hey there. I’m <a class="LOGO" href="https://github.com/ABDULALI3468">Abdul Ali.</a>
>
> +                <span>I’m a software developer</span>
>
> +            </h1>
>
>
>
>    - (Optional) Nice attempt trying to implement the changes suggested by
>    a previous reviewer. I think it would be nice to wrap the text *I'm a
>    software developer* in a <p> tag instead of a span tag. <span> tags
>    are not block-level elements, so whenever they are used, they appear inline
>    of their parent element on a web page. Try to make your design identical to
>    the Figma template you chose.
>
> Your Design
>
> [image: image]
> <https://user-images.githubusercontent.com/77106962/159144613-4b8f4d3d-e1cf-4675-a965-43068fb3e45b.png>
> Figma Design
>
> [image: image]
> <https://user-images.githubusercontent.com/77106962/159144625-bc4b3723-1404-4490-8826-a83c5c5d369b.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ABDULALI3468/MY_PORTFOLIO/pull/1#pullrequestreview-915048746>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWO3YB3BN6CE23SVOURBBNTVA2ARDANCNFSM5Q6QFTQQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-03-22 17:00 UTC, merged