Popup window and cards creation using javascript.
ABDULALI3468/MY_PORTFOLIO pull request #23
Opened 2022-04-08 10:51 UTC by ABDULALI3468

In this project, I have created cards for my portfolio project and added functionality to the button of the cards that will make a pop-up window appear on the entire screen.

2022-04-08 18:59 UTC, Hope1226 requested changes
Hi @ABDULALI3468 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Required Changes ♻️

- [ ]  Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- n/a

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-08 18:59 UTC, Hope1226 commented on popup.js
> +];
[REQUIRED] Nice work on making a function for creating a card :+1:  However, as you might have already known, the above function creates cards with the same content every time it gets invoked. Considering you are creating such `cards` 6 times using `loop` in lines `47..49`, You are creating 6 cards with exactly the same content. That is not practical and does not meet the tech requirements of this milestone.

- [ ] As required by this `milestone`, please create cards dynamically using your `projects` array which stores project data in a form of `objects`. There is a much simpler way of doing it compared to the above code created by your side, I will give you some guidelines here, but you can decide whether to refactor the codebase or make the existing one work.

**_hints:_**

**Step-1**: Make sure the values of the project `objects` within the `array list` are correct and make sure you have multiple project objects within your array list (now I can see only one).

**Step-2**: Select the main container for your cards, I think, it is already selected as  `gridContainer`.

**Step-3**: Now we can iterate through our `array list`. You have many options like `for loop`, `forEach`, `map` and etc. You can go with either option depending on your convenience. I am gonna use `map` for this particular case. So we are looping the `array` each `element` is an object, in order to get the value from the object you can specify the appropriate key, something like `element.name`. Now keeping the above information in mind, we need to create an `HTML` element (project card) in each iteration and `append` it to our main container (mentioned in step-2).

_sample code:_
```JAVASCRIPT

gridContainer.innerHTML += projects.map((project) => {
return ( 
` <div class="projectCard">
        <img src=${project.image} alt="project screenshot">
        <div class="project-description">
          <h3 class="project-title">${project.title}</h3>
          <ul>
          // you can use the same logic to create `<li/>` tags dynamically with the array of techs
          </ul>
          <button type="button" class="see-project-btn">See this porject</button>
        </div>
      </div>
    </div>
  `)
}).join('');
```
**Step-4**: Make sure your static `project cards` from your [index.html](https://github.com/ABDULALI3468/MY_PORTFOLIO/blob/popup_window/index.html) are removed. I hope it is working as expected :pray:

_note:_  You can use the same logic with any other `loop`. Please note that the above code is not a direct solution, it is just a sample code to demonstrate the above-mentioned steps, which you need to modify based on your project.

**Important** Please make sure your `popup` window is functioning as expected after respective changes are introduced

2022-04-09 11:38 UTC, phelian23 requested changes

2022-04-09 11:38 UTC, phelian23 commented on popup.js
> +
- [ ] Good job adding the projects array and using it to populate the pop-up modal 👍. However, as requested by the previous reviewer, it is a requirement that the cards of the project section (grid container) also should be populated with the details from the projects array. Kindly make sure the content of the cards is from the projects array. The idea is that when the time comes for you to add projects to your portfolio, you only need to add the project object to the projects array. You can give each object the same title so it will be consistent with the design template.

2022-04-09 11:38 UTC, phelian23 commented on popup.js
> +  console.log('iside creat pop');
- [ ] [Optional] It is a good practice not to commit `console.log` with your code. kindly remove it.

2022-04-09 11:38 UTC, phelian23 commented on popup.js
> +    console.log('loop throw tech list');
- [ ] [Optional] It is a good practice not to commit `console.log` with your code. kindly remove it.

2022-04-09 11:38 UTC, phelian23 commented on popup.js
> +    console.log(divli);
- [ ] [Optional] It is a good practice not to commit `console.log` with your code. kindly remove it.

2022-04-09 11:38 UTC, phelian23 commented on popup.js
> +    console.log(divul);
- [ ] [Optional] It is a good practice not to commit `console.log` with your code. kindly remove it.

2022-04-09 11:38 UTC, phelian23 commented on popup.js
> +    console.log('show popup');
- [ ] [Optional] It is a good practice not to commit `console.log` with your code. kindly remove it.

2022-04-09 11:38 UTC, phelian23 commented on popup.css
> +
- [ ] [Optional] The popup image is too big, and it fits the entire screen. The popup modal width should be around 80% of the view width and its height should be around 90% of the view height. Kindly fix this so that your design matches that of the template as much as possible.
Your design
![Capture](https://user-images.githubusercontent.com/85095702/162572441-2f78e182-825a-4e19-8a13-2d9f2991ff98.PNG)

Figma template
![figma](https://user-images.githubusercontent.com/85095702/162572463-bd9a7e4e-6913-4a43-ac0e-f0ccc4f42310.PNG)

2022-04-09 11:41 UTC, phelian23 requested changes
Hi @Team, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-09 11:50 UTC, phelian23 requested changes
Hi @Team, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-09 11:50 UTC, phelian23 commented on popup.js
> +
- [ ] Good job adding the projects array and using it to populate the pop-up modal 👍. However, as requested by the previous reviewer, it is a requirement that the cards of the project section (grid container) also should be populated with the details from the projects array. Kindly make sure the content of the cards is from the projects array. The idea is that when the time comes for you to add projects to your portfolio, you only need to add the project object to the projects array. You can give each object the same title so it will be consistent with the design template.

2022-04-09 11:50 UTC, phelian23 commented on popup.js
> +  console.log('iside creat pop');
- [ ] [Optional] It is a good practice not to commit `console.log` with your code. kindly remove it.

2022-04-09 11:50 UTC, phelian23 commented on popup.js
> +    console.log('loop throw tech list');
- [ ] [Optional] It is a good practice not to commit `console.log` with your code. kindly remove it.

2022-04-09 11:50 UTC, phelian23 commented on popup.js
> +    console.log(divli);
- [ ] [Optional] It is a good practice not to commit `console.log` with your code. kindly remove it.

2022-04-09 11:50 UTC, phelian23 commented on popup.js
> +    console.log(divul);
- [ ] [Optional] It is a good practice not to commit `console.log` with your code. kindly remove it.

2022-04-09 11:50 UTC, phelian23 commented on popup.js
> +    console.log('show popup');
- [ ] [Optional] It is a good practice not to commit `console.log` with your code. kindly remove it.

2022-04-09 11:50 UTC, phelian23 commented on popup.css
> +}
- [ ] [Optional] The popup image is too big, and it fits the entire screen. The popup modal width should be around 80% of the view width and its height should be around 90% of the view height. Kindly fix this so that your design matches that of the template as much as possible.
Your design
![Capture](https://user-images.githubusercontent.com/85095702/162572441-2f78e182-825a-4e19-8a13-2d9f2991ff98.PNG)

Figma template
![figma](https://user-images.githubusercontent.com/85095702/162572463-bd9a7e4e-6913-4a43-ac0e-f0ccc4f42310.PNG)

2022-04-09 20:59 UTC, aimemalaika approved these changes
Hi @ABDULALI3468 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![133591850-fdcb7dd3-dd7a-4274-81e7-0e59434148f7](https://user-images.githubusercontent.com/28307960/158747852-e9f4c957-d810-4de4-b468-69b1337714ea.png)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-09 06:33 UTC, merged